name: zren
description: A lightweight Flutter framework for type-safe form handling, async state management, and MVVM patterns.
version: 0.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
